name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dev tools
        run: |
          npm init -y
          npm install --save-dev html-validate

      - name: Validate HTML
        run: npx html-validate index.html

      - name: Check for broken links (basic grep)
        run: |
          grep -E 'href="|src="' index.html || true

      - name: Run security checks (fail on secrets)
        run: |
          ! grep -E 'api_key|password|secret' *.js *.html

      - name: Build site (add timestamp)
        run: |
          echo "window.BUILD_TIME='$(date)';" > build-info.js
          cat script.js >> build-info.js
          mv build-info.js script.js

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .